### ISSUE TITLE
HTML output?

### ISSUE THREAD

**Issue by mmkal** [eslint/config-inspector#19]
Hi - just discovered this yesterday and it is extremely helpful! I would love to incorporate it into CI at work. When our playwright tests fail, we output the results HTML folder which is then statically served by our CI provider. It'd be great to be able to run a command like `npx @eslint/config-inspector --outDir dist/eslint-config` after our CI lint job fails. I'm imagining that would  dump some HTML/JS/CSS files into a folder so that it can be served as a webpage (like [playwright](https://playwright.dev/docs/test-reporters#html-reporter)).

Would this be possible? I haven't looked into whether the filtering is happening server-side or client-side. If it's server-side, it might not be so easy.

**Comment by antfu** [comment]
It's already implemented in https://github.com/eslint/config-inspector/pull/17, just haven't released yet
