### ISSUE TITLE
List lintable files?

### ISSUE THREAD

**Issue by mmkal** [eslint/config-inspector#24]
Hi - not sure if this is within the scope of this library, or whether it _could_ be if it isn't.

I have an eslint command on a fairly large project that's hanging seemingly forever. Based on past experience, this might be because eslit is trying to find all the files in some huge generated folder.

Could this tool show all the files that eslint will pick up? That way, it'd be easier to spot when we're accidentally linting unwanted paths.

I'd imagine it could be done by iterating through the configs and checking the various `files` globs, then running fast-glob on them?

**Comment by antfu** [comment]
It actually already has that information:

<img width="593" alt="Screenshot 2024-04-05 at 10 43 03" src="https://github.com/eslint/config-inspector/assets/11247099/ddf9a182-34b6-4a9e-8a11-7fd6070f2811">

But only used as autocomplete at this moment - would need to think more about how we could present it in a dedicate view of different ways

**Comment by mmkal** [comment]
How about another two, next to `Config` and `Rules`, named `Files`. The searchbar could filter down based on the user's glob input, and clicking a file path could show the configs that do/don't apply to it.

It might be useful too to be able to also search for files that aren't linted, so the UI could show either "no files found" or if a file exists but isn't linted, highlight the config that told eslint to ignore it. That would help when re-exporting flat configs from another library, which has too many `ingores`, say.

**Comment by mmkal** [comment]
Wow - that was fast. Looking forward to trying it. 🚀🚀🚀
