### ISSUE TITLE
Inspector hangs on load

### ISSUE THREAD

**Issue by Xiot** [eslint/config-inspector#31]
When loading up the inspector webpage, it seems to be stuck in an infinite loop

I see this in the console, and the browser tab is pegged at `100%`.

![CleanShot 2024-04-07 at 11 10 27@2x](https://github.com/eslint/config-inspector/assets/1887318/911c8d4c-7c06-4be0-b3bc-ddc84ac02d84)

I'm still on `eslint@npm:8.56.0`, but have migrated to the flat config.  
I was originally having this issue yesterday as well, but it seemed to fix itself at some point, and now it is back to hanging.

**Comment by antfu** [comment]
It seems like a browser extension you have? Or, can you share a minimal reproduction?

**Comment by Xiot** [comment]
I just tried in an incognito window (Chrome 123.0.6312.87 on MacOS) and I got the same thing.

Unfortunately its happening on my private monorepo, but I'll see if I can reproduce it elsewhere

**Comment by Xiot** [comment]
I was able to capture a [trace](https://share.firefox.dev/4aqVYbS) with Firefox, and the page eventually does become intractable in about 25s.  It looks like most of the time is spent transforming the globs to regex.

A bunch of the globs that I'm using in my `eslint.config.js` are built up from the `includes` from my `tsconfig.json` files.

**Comment by Xiot** [comment]
It appears that it due the length of the `files` array from `payload.json`.  
I built the site, and removed all files, except for 1, and the page loaded up instantly.

I also noticed that the `files` array didn't include all of my files either

**Comment by antfu** [comment]
Can you check if v0.4.4 improves it? Thanks

**Comment by Xiot** [comment]
That is much better.  Thanks!
