### ISSUE TITLE
Pressing enter on the filter bar resets the value to the one used for the last search

### ISSUE THREAD

**Issue by haykam821** [eslint/config-inspector#35]
Using version 0.4.3, when typing in the filter bar, the enter key seems to have an effect even though filtered results update automatically. Whichever value was last used as a filter (shown in the 'Filepath is not included or has been ignored' message) will replace the current value. I would expect the value to stay the same if no completion could be found for the given value.

**Comment by antfu** [comment]
I am not sure if I understand - Can you explain more or show some examples?
