### ISSUE TITLE
When my eslint configuration file is ".eslintrc.cjs", I run "npx @eslint/config-inspector", I get the following error 🤔

### ISSUE THREAD

**Issue by wangrongding** [eslint/config-inspector#42]
![image](https://github.com/eslint/config-inspector/assets/42437658/c73f1a26-6396-4076-badd-a56194f48d2e)

Will there be support for using .eslintrc.cjs later?

**Comment by antfu** [comment]
As printed, config inspector only works for flat config. eslintrc is not supported.
