### ISSUE TITLE
Install and Use as a Dependency

### ISSUE THREAD

**Issue by Barzi-Ahmed** [eslint/config-inspector#43]
Hello,

This is a great project and idea, but I would like to use config-inspector not as npx, but rather install it as devdepdency and use it as something like "npm run inspect" or "npm run insepct:reload" etc.

**Comment by antfu** [comment]
You can. Just install it as devDeps and add scripts:

```json
{
  "scripts": {
    "inspect": "eslint-config-inspector"
  },
  "devDependencies": {
    "@eslint/config-inspector": "*"
  }
}
```
