### ISSUE TITLE
[BUG] Doesn't work when the config is outside of `C:` drive on Windows

### ISSUE THREAD

**Issue by EDM115** [eslint/config-inspector#47]
## Description

When the project is located on another drive, here's the error :  
```
Failed to load eslint.config.js
Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'd:'
```

## Screenshot

![image](https://github.com/eslint/config-inspector/assets/82015596/4ca7762a-0332-4008-9eec-792f336f2c51)

## Reproducible scenario

- Create a new nuxt project on another drive than C
- Add an eslint config (flat format here)
- Run the dev server, check the nuxt devtools and observe the above screenshot

**Comment by EDM115** [comment]
here's what reports the Nuxt devtools terminal :
```bash
> node D:/EDM115/Documents/IUT/SAE 3.A.01/Tab-Magiques/node_modules/@eslint/config-inspector/bin.mjs --no-open

ℹ Starting ESLint config inspector at http://127.0.0.1:8123 

ℹ Reading ESLint config from D:\EDM115\Documents\IUT\SAE 3.A.01\Tab-Magiques\eslint.config.js
Failed to load `eslint.config.js`.
Note that `@eslint/config-inspector` only works with the flat config format:
https://eslint.org/docs/latest/use/configure/configuration-files-new
Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'd:'
    at throwIfUnsupportedURLScheme (node:internal/modules/esm/load:239:11)
    at defaultLoad (node:internal/modules/esm/load:130:3)
    at ModuleLoader.load (node:internal/modules/esm/loader:403:13)
    at ModuleLoader.moduleProvider (node:internal/modules/esm/loader:285:56)
    at new ModuleJob (node:internal/modules/esm/module_job:67:26)
    at #createModuleJob (node:internal/modules/esm/loader:297:17)
    at ModuleLoader.getJobFromResolveResult (node:internal/modules/esm/loader:254:34)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:235:17)
    at async ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:87:21) {
  code: 'ERR_UNSUPPORTED_ESM_URL_SCHEME'
}
```

**Comment by meirroth** [comment]
I'm experiencing the same issue on Windows.

**Comment by antfu** [comment]
It's likely a bug of https://github.com/egoist/bundle-require - if any one wants to help fixing it

**Comment by LittleTurtle2333** [comment]
same issue

**Comment by Mallon94** [comment]
I don't think its related to what drive its on. Happens on any drive. Seems to be that withNuxt isn't getting imported correctly.

**Comment by Mallon94** [comment]
To fix this temporarily, you can replace the contents of your eslint.config.mjs with the below;

```javascript
import { pathToFileURL } from 'url';
const fileURL = pathToFileURL('./.nuxt/eslint.config.mjs');
const withNuxt = await import(fileURL.href);

export default withNuxt.default({
 // custom config
})

**Comment by EDM115** [comment]
> withNuxt isn't getting imported correctly

honestly I don't even know why the documentation recommends using it. it requires the app to be built (to generate the .nuxt folder) before even be able to start linting

> To fix this temporarily you can use pathToFileURL to get the correct file path then import with that

I get the idea, but I think a better thing would be to use another import :

```js
import { createConfigForNuxt } from '@nuxt/eslint-config/flat'

export default createConfigForNuxt(
  // config...
)
```

I don't see the benefit of using `withNuxt` over `createConfigForNuxt`, and on another topic I believe the [documentation](https://eslint.nuxt.com/packages/module#manual-setup) should recommend that way

**Comment by meirroth** [comment]
@antfu Thank you for fixing this issue ❤
