### ISSUE TITLE
Ligatures affecting readability

### ISSUE THREAD

**Issue by haydenbleasel** [eslint/config-inspector#73]
![CleanShot 2024-06-29 at 16 41 52@2x](https://github.com/eslint/config-inspector/assets/4142719/2d3e49cd-fc44-49db-90a0-e5a1f46b348e)

Space Mono doesn't have perfect ligatures IMO.

You can fix this by adding `font-variant-ligatures: none;` to the root element.

**Comment by antfu** [comment]
Yeah I'd agree - PR welcome!
