### ISSUE TITLE
`nth` function breaks on large numbers, causing inconsistencies

### ISSUE THREAD

**Issue by pauliesnug** [eslint/config-inspector#74]
the current implementation of `nth` is as follows:
```ts
export function nth(n: number) {
  if (n === 1)
    return '1st'
  if (n === 2)
    return '2nd'
  if (n === 3)
    return '3rd'
  return `${n}th`
}
```

this leads to issues like this:
![image](https://github.com/eslint/config-inspector/assets/66741050/a4c626a0-43d3-41f7-bb3b-9fc8b399ec9e)

i can submit a PR to fix this if needed. maybe we use a small devdepencency library?

**Comment by voxpelli** [comment]
Agree, made a PR to fix 👍
