### ISSUE TITLE
Error in the label condition

### ISSUE THREAD

**Issue by AlexRMU** [eslint/config-inspector#80]
The patterns act as global ignores if an ignores key is used without any other keys in the configuration object.
https://eslint.org/docs/latest/use/configure/ignore#ignoring-files
https://github.com/eslint/config-inspector/blob/7720a12e9dbc911d922dfcd6f933add666120fa2/app/components/ConfigItem.vue#L150-L152

**Comment by antfu** [comment]
What do you suggest? Would we instead output "Invalid config item" or something? Without `files` I guess `ignores` are meaningless if not being global.

**Comment by AlexRMU** [comment]
Yes.
- if there is a key `ignores`
    - if there is a key `files`
        - this is a regular configuration object
    - else
        - If there are other keys here
            - show an error
        - else
            - this is an global ignore object

**Comment by voxpelli** [comment]
Why show an error when `files` is missing?

It's valid to have a config like:

```js
export default [
  {
    files: ['lib/**/*.foo'],
    rules: {
      // Rules for lib/**/*.foo
    }
  },
  {
    ignores: ['lib/**/*.foo'],
    rules: {
      // Rules for everything but lib/**/*.foo
    }
  }
];
```

**Comment by AlexRMU** [comment]
Yes.
Edited.
